#!/usr/bin/env bash
# Writes web/js/wss_proxy_worker_config.js from WEB_WSS_PROXY_URL in .env.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT_DIR}/web/js/wss_proxy_worker_config.js"
ENV_FILE="${ROOT_DIR}/.env"

WSS_URL=""
if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1090
  set -a
  source "${ENV_FILE}"
  set +a
fi
WSS_URL="${WEB_WSS_PROXY_URL:-}"

ENABLED="false"
if [[ -n "${WSS_URL}" ]]; then
  ENABLED="true"
fi

python3 - "${OUT}" "${ENABLED}" "${WSS_URL}" <<'PY'
import json
import sys

out, enabled, url = sys.argv[1], sys.argv[2] == "true", sys.argv[3]
config = json.dumps({"enabled": enabled, "url": url}, ensure_ascii=False)
content = f"""// Generated by scripts/generate-wss-worker-config.sh — do not edit by hand.
self.RIOGRAM_WSS_CONFIG = {config};
"""
open(out, "w", encoding="utf-8").write(content)
PY

echo "✅ ${OUT} (enabled=${ENABLED}, url=${WSS_URL:-<auto same-origin>})"
